Repository implementation using PostGreSql DB
bjedrzejewski/chessmates pull request #60
Opened 2017-04-25 13:55 UTC by ZinatWali

I think some of the tests are broken. I am going to review the tests next. And I will also investigate places where findById is being invoked. As I am returning list of objects from findById, that might not be the desired behaviour.

2017-04-25 15:29 UTC, bjedrzejewski requested changes
Hi @ZinatWali thanks for that PR, really good work! I have some minor comments and queries

2017-04-25 15:29 UTC, bjedrzejewski commented on src/main/java/com/chessmates/repository/MockGameRepository.groovy
> +    def findAll() {
Why do we change it to def? Maybe having List is useful as it lets use use some type chacking? What do you think?

2017-04-25 15:29 UTC, bjedrzejewski commented on src/main/java/com/chessmates/repository/MockPlayerRepository.groovy
> +    def find(Object playerId) {
Why not expect a String here?

2017-04-25 15:29 UTC, bjedrzejewski commented on src/main/java/com/chessmates/repository/RdsQueryExecutor.groovy
> +class RdsQueryExecutor implements QueryExecutor {
I really like the design of this class! 👍

2017-04-25 15:29 UTC, bjedrzejewski commented on src/main/resources/application.properties
> +chessmates.rds.hostName = chessmates-rds.chrwglr5bu8k.eu-west-1.rds.amazonaws.com
Can we somehow avoid storing that in the app properties? It feels like this should be a secret as well.

2017-04-25 15:44 UTC, bjedrzejewski commented
I think we may need to set up some parameters in Travis. If this is the case, just let me know on Slack.

2017-04-25 17:32 UTC, janakerman requested changes
Looking good - few comments.

2017-04-25 17:32 UTC, janakerman commented on src/main/java/com/chessmates/lichess/data/LichessDataServiceImpl.groovy
> +        playerRepository.&saveAll(players)
We only need to pass a method reference when we're wanting to provide a class method as a parameter to another function. You can just call it directly here:
`playerRepository.saveAll(players)`

2017-04-25 17:32 UTC, janakerman commented on src/main/java/com/chessmates/lichess/data/LichessDataServiceImpl.groovy
> +                gameRepository.&saveAll(games)
As above.

2017-04-25 17:32 UTC, janakerman commented on src/main/java/com/chessmates/repository/MockGameRepository.groovy
>          store.put(game.id, game)
Don't we need putAll or something of the like? I'm not sure this would leave our get game / game player API working.

2017-04-25 17:32 UTC, janakerman commented on src/main/java/com/chessmates/repository/MockGameRepository.groovy
> +    def findAll() {
On second thoughts, this isn't inconsistency as I said the other day. This used to be `List<Player>` and as we removed our model objects it became `List<Object>` aka List. Since this is class API, I still think we want to type things where known, and this will be a list so we can type it.

2017-04-25 17:32 UTC, janakerman commented on src/main/java/com/chessmates/repository/MockGameRepository.groovy
>          store.put(game.id, game)
Also I think this should be save(game**s**) right?

2017-04-25 17:32 UTC, janakerman commented on src/main/java/com/chessmates/repository/MockGameRepository.groovy
> -    void save(game) {
I don't see any reason not to keep save(game) on the repository.

2017-04-25 17:32 UTC, janakerman commented on src/main/java/com/chessmates/repository/MockPlayerRepository.groovy
> -    void save(player) {
Same comments above as above for this class.

2017-04-25 17:32 UTC, janakerman commented on src/main/java/com/chessmates/repository/RdsQueryExecutor.groovy
> +        (queryStatement,resultSet) = handleEmbeddedQueryUsing(conn)
nice!

2017-04-25 17:32 UTC, janakerman commented on src/main/java/com/chessmates/repository/RdsQueryExecutor.groovy
> +        //lambda placeholder
Placeholder for? If item is a ResultSet we return an result of the populateOutputObject function (a list?) If it isn't we return a function?

2017-04-25 17:32 UTC, janakerman commented on src/main/java/com/chessmates/repository/RdsQueryExecutor.groovy
> +    def executeSelect(givenTableName, givenId = null) {
I'd probably type this for documentation purposes as it is a public method. I've only really relied on weak typing where a plain object is being returned. Looks like it is a List right?

2017-04-25 17:32 UTC, janakerman commented on src/test/java/com/chessmates/lichess/data/LichessDataServiceImplTest.groovy
> +        1 * playerRepository.saveAll(_)
Do we still want to test that the thing we are saving is what we expect?
```
1 * playerRepository.saveAll({
    it[0].id == 'jfaker' &&
    ... // so forth
})
```

There's probably a nicer way than what I've done above.

2017-04-25 17:32 UTC, janakerman commented on src/test/java/com/chessmates/lichess/data/LichessDataServiceImplTest.groovy
> +        1 * gameRepository.saveAll(_)
To keep the same logic here we'd want to be checking the list passed to saveAll has a length of 56.

2017-04-27 09:43 UTC, janakerman commented on src/test/java/com/chessmates/lichess/data/LichessDataServiceImplTest.groovy
> +        3 * gameRepository.saveAll(_)
Why do we now expect the games to be saved three times?

2017-04-27 09:44 UTC, janakerman commented on src/test/java/com/chessmates/lichess/data/LichessDataServiceImplTest.groovy
>          MetaDataRepository metaDataRepository() {
Did you decide to pull out the spring dependency form these tests?

2017-04-27 12:37 UTC, ZinatWali commented on src/main/java/com/chessmates/repository/MockGameRepository.groovy
> -    void save(game) {
When I looked through code, it seemed like we are storing whatever we are receiving from lichess API - anything after the last saved. This use case can be served by saveAll() alone. That is what I thought.

2017-04-27 12:37 UTC, ZinatWali commented on src/main/java/com/chessmates/repository/MockGameRepository.groovy
>          store.put(game.id, game)
What would be the functionality of putAll()?

2017-04-27 12:39 UTC, ZinatWali commented on src/main/java/com/chessmates/repository/RdsQueryExecutor.groovy
> +        //lambda placeholder
Re-organised the code in this area a bit. I had a misunderstanding of groovy's ternary operator.

2017-04-27 13:17 UTC, janakerman commented on src/main/java/com/chessmates/repository/MockGameRepository.groovy
> -    void save(game) {
It is - you can remove if you like. My comment was just that it is feasible that in the future saving a single game may make sense. I really don't feel strongly about this so consider this resolved.

2017-04-27 13:20 UTC, janakerman commented on src/main/java/com/chessmates/repository/MockGameRepository.groovy
>          store.put(game.id, game)
Well -
saveAll(games) <- takes a list of games right? How can we get the id off a list of games? We'd need to do something like this?

```
games.each { store.put(it.id, it) }
```

If you'd rather remove this class instead - feel free!

p.s. put all makes no sense ignore that.

2017-04-27 13:23 UTC, janakerman commented on src/main/java/com/chessmates/repository/RdsQueryExecutor.groovy
> +        if(!(item instanceof ResultSet)) return
Do we want to return an empty list instead?

2017-04-27 13:29 UTC, bjedrzejewski approved these changes

2017-04-27 13:36 UTC, ZinatWali commented on src/main/java/com/chessmates/repository/RdsQueryExecutor.groovy
> +        if(!(item instanceof ResultSet)) return
In this case it doesn't really matter what is returned. This 'return' will only execute for Insert queries and we are not doing anything with the return value for inserts.

2017-04-28 07:56 UTC, janakerman commented on src/main/java/com/chessmates/repository/RdsQueryExecutor.groovy
> +        if(!(item instanceof ResultSet)) return
Confused as to how this executes for insert queries? The `stmt` above is a SELECT statement?

2017-04-28 15:12 UTC, merged